<ul id="dropmenu1" class="dropMenu">

  

</ul><ul id="dropmenu2" class="dropMenu">

    <li><a href="http://localhost/a/zhuangshiban/">装饰板</a></li>

    <li><a href="http://localhost/a/jinshuzhuangshixiantiao/">金属装饰线条</a></li>

    <li><a href="http://localhost/a/jinshuzhuangshiban/">金属装饰板</a></li>

    <li><a href="http://localhost/a/zhiganzhuangshishajiang/">质感装饰砂浆</a></li>

    <li><a href="http://localhost/a/ganhunshajiang/">干混砂浆</a></li>

  

</ul><ul id="dropmenu3" class="dropMenu">

    <li><a href="http://localhost/solution/warm/">建筑外墙保温领域</a></li>

    <li><a href="http://localhost/solution/common/">公共内装领域</a></li>

    <li><a href="http://localhost/solution/family/">家庭装饰领域</a></li>

    <li><a href="http://localhost/solution/ground/">地下空间领域</a></li>

    <li><a href="http://localhost/solution/steelwork/">钢结构建筑外围护领域</a></li>

    <li><a href="http://localhost/solution/clean/">洁净房领域</a></li>

  

</ul><ul id="dropmenu4" class="dropMenu">

  

</ul><ul id="dropmenu5" class="dropMenu">

    <li><a href="http://localhost/news/company/">公司动态</a></li>

    <li><a href="http://localhost/news/industry/">行业动态</a></li>

  

</ul><ul id="dropmenu6" class="dropMenu">

  

</ul>