<ul id="dropmenu1" class="dropMenu">

  

</ul><ul id="dropmenu35" class="dropMenu">

    <li><a href="http://localhost/product_center/huanbaocailiao/">环保材料</a></li>

    <li><a href="http://localhost/product_center/gongyibiaozhun/">工艺标准</a></li>

    <li><a href="http://localhost/product_center/shigongguanli/">施工管理</a></li>

  

</ul><ul id="dropmenu30" class="dropMenu">

    <li><a href="http://localhost/solution/gongzhuang/">工程装修</a></li>

    <li><a href="http://localhost/solution/jiazhuang/">家庭装修</a></li>

  

</ul><ul id="dropmenu4" class="dropMenu">

    <li><a href="http://localhost/cases/gongzhuang/">工装案例</a></li>

    <li><a href="http://localhost/cases/jiazhuang/">家装案例</a></li>

  

</ul><ul id="dropmenu5" class="dropMenu">

    <li><a href="http://localhost/news/company/">公司动态</a></li>

    <li><a href="http://localhost/news/industry/">行业动态</a></li>

  

</ul><ul id="dropmenu39" class="dropMenu">

    <li><a href="http://localhost/contract_us/">联系我们</a></li>

    <li><a href="http://localhost/join_us/">加入我们</a></li>

  

</ul>