<ul id="dropmenu1" class="dropMenu">

  

</ul><ul id="dropmenu2" class="dropMenu">

    <li><a href="http://localhost/a/zhuangshiban/">装饰板</a></li>

    <li><a href="http://localhost/a/jinshuzhuangshixiantiao/">金属装饰线条</a></li>

    <li><a href="http://localhost/a/jinshuzhuangshiban/">金属装饰板</a></li>

    <li><a href="http://localhost/a/zhiganzhuangshishajiang/">质感装饰砂浆</a></li>

    <li><a href="http://localhost/a/ganhunshajiang/">干混砂浆</a></li>

  

</ul><ul id="dropmenu30" class="dropMenu">

    <li><a href="http://localhost/solution/gongzhuang/">工程装修</a></li>

    <li><a href="http://localhost/solution/jiazhuang/">家庭装修</a></li>

  

</ul><ul id="dropmenu4" class="dropMenu">

    <li><a href="http://localhost/cases/gongzhuang/">工装案例</a></li>

    <li><a href="http://localhost/cases/jiazhuang/">家装案例</a></li>

  

</ul><ul id="dropmenu5" class="dropMenu">

    <li><a href="http://localhost/news/company/">公司动态</a></li>

    <li><a href="http://localhost/news/industry/">行业动态</a></li>

  

</ul><ul id="dropmenu6" class="dropMenu">

  

</ul>