<?php
$tmpdir = "be39798ffbf2f1f0";
$vtime = 20140814;
$files[0] = "include/dedesql.class.php";
$files[1] = "include/dedesqli.class.php";
$files[2] = "include/shopcar.class.php";
$files[3] = "dede/config.php";
$files[4] = "plus/recommend.php";
$files[5] = "include/datalistcp.class.php";
$files[6] = "member/config.php";
$files[7] = "dede/soft_edit.php";
$files[8] = "member/buy_action.php";
$files[9] = "member/album_edit.php";
$files[10] = "member/soft_edit.php";
$fileConut = 10;
$sqls[] = "20140606.sql";
$sqls[] = "20140612.sql";
$sqls[] = "20140623.sql";
$sqls[] = "20140627.sql";
$sqls[] = "20140724.sql";
$sqls[] = "20140725.sql";
$sqls[] = "20140814.sql";
?>