<?php
$z[0]=Array("item","",6,160);
$z[0][4]['name']="普通文章";
$z[0][4]['ischannel']="1";
$z[0][4]['link']="content_list.php?channelid=1";
$z[0][4]['linkadd']="article_add.php?channelid=1";
$z[0][4]['channelid']="1";
$z[0][4]['rank']="";
$z[0][4]['target']="main";
$z[1]=Array("item","",169,247);
$z[1][4]['name']="在线订单";
$z[1][4]['link']="diy_main.php";
$z[1][4]['rank']="c_List";
$z[1][4]['target']="main";

?>