<?php
$z[0]=Array("item","",4,83);
$z[0][4]['name']="E站酷";
$z[0][4]['link']="http://www.ezhanku.com";
$z[0][4]['rank']="";
$z[0][4]['target']="_blank";
$z[1]=Array("item","",87,171);
$z[1][4]['name']="网站模板";
$z[1][4]['link']="http://www.ezhanku.com";
$z[1][4]['rank']="";
$z[1][4]['target']="_blank";
$z[2]=Array("item","",175,268);
$z[2][4]['name']="织梦模板";
$z[2][4]['link']="http://www.ezhanku.com/dedecms/";
$z[2][4]['rank']="";
$z[2][4]['target']="_blank";

?>