<?php
$z[0]=Array("field","",240,262);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",302,354);
$z[1][4]['name']="description";
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("field","",779,798);
$z[2][4]['name']="title";
$z[3]=Array("global","",799,825);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",929,964);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",978,1014);
$z[5][4]['filename']="head2.htm";
$z[6]=Array("field","",1312,1331);
$z[6][4]['name']="title";
$z[7]=Array("field","",1369,1425);
$z[7][4]['name']="pubdate";
$z[7][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[8]=Array("field","",1477,1504);
$z[8][4]['name']="phpurl";
$z[9]=Array("field","",1528,1551);
$z[9][4]['name']="id";
$z[10]=Array("field","",1556,1580);
$z[10][4]['name']="mid";
$z[11]=Array("field","",1746,1764);
$z[11][4]['name']="body";
$z[12]=Array("type","<a class=\"\" href=\"[field:typeurl/]\">返回上级</a>",1826,1912);
$z[12][4]['typeid']="5";
$z[13]=Array("include","",1943,1980);
$z[13][4]['filename']="footer.htm";

?>