<?php
$z[0]=Array("field","",242,264);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",304,356);
$z[1][4]['name']="description";
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("field","",781,800);
$z[2][4]['name']="title";
$z[3]=Array("global","",801,827);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",931,966);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",980,1016);
$z[5][4]['filename']="head2.htm";
$z[6]=Array("field","",1314,1333);
$z[6][4]['name']="title";
$z[7]=Array("field","",1371,1427);
$z[7][4]['name']="pubdate";
$z[7][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[8]=Array("field","",1479,1506);
$z[8][4]['name']="phpurl";
$z[9]=Array("field","",1530,1553);
$z[9][4]['name']="id";
$z[10]=Array("field","",1558,1582);
$z[10][4]['name']="mid";
$z[11]=Array("field","",1748,1766);
$z[11][4]['name']="body";
$z[12]=Array("type","<a class=\"\" href=\"[field:typeurl/]\">返回上级</a>",1828,1914);
$z[12][4]['typeid']="5";
$z[13]=Array("include","",1945,1982);
$z[13][4]['filename']="footer.htm";

?>