<?php
$z[0]=Array("field","",199,221);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",261,313);
$z[1][4]['name']="description";
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("field","",738,757);
$z[2][4]['name']="title";
$z[3]=Array("global","",758,784);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",888,923);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",937,973);
$z[5][4]['filename']="head2.htm";
$z[6]=Array("field","",1164,1183);
$z[6][4]['name']="title";
$z[7]=Array("field","",1221,1277);
$z[7][4]['name']="pubdate";
$z[7][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[8]=Array("field","",1329,1356);
$z[8][4]['name']="phpurl";
$z[9]=Array("field","",1380,1403);
$z[9][4]['name']="id";
$z[10]=Array("field","",1408,1432);
$z[10][4]['name']="mid";
$z[11]=Array("field","",1610,1628);
$z[11][4]['name']="body";
$z[12]=Array("type","<a class=\"\" href=\"[field:typeurl/]\">返回上级</a>",1697,1783);
$z[12][4]['typeid']="4";
$z[13]=Array("include","",1814,1851);
$z[13][4]['filename']="footer.htm";

?>