<?php
$z[0]=Array("field","",199,221);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",261,313);
$z[1][4]['name']="description";
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("field","",738,757);
$z[2][4]['name']="title";
$z[3]=Array("global","",758,784);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",890,925);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",938,974);
$z[5][4]['filename']="head2.htm";
$z[6]=Array("field","",1084,1106);
$z[6][4]['name']="typename";
$z[7]=Array("type","[field:enwords /]",1131,1182);
$z[7][4]['typeid']="6";
$z[8]=Array("field","",1259,1278);
$z[8][4]['name']="title";
$z[9]=Array("field","",1318,1374);
$z[9][4]['name']="pubdate";
$z[9][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[10]=Array("field","",1390,1408);
$z[10][4]['name']="body";
$z[11]=Array("type","<a class=\"\" href=\"[field:typeurl/]\">返回上级</a>",1466,1552);
$z[11][4]['typeid']="6";
$z[12]=Array("include","",1574,1611);
$z[12][4]['filename']="footer.htm";

?>