<?php
$z[0]=Array("field","",242,264);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",304,356);
$z[1][4]['name']="description";
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("field","",781,800);
$z[2][4]['name']="title";
$z[3]=Array("global","",801,827);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",931,966);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",980,1016);
$z[5][4]['filename']="head2.htm";
$z[6]=Array("field","",1314,1333);
$z[6][4]['name']="title";
$z[7]=Array("field","",1371,1427);
$z[7][4]['name']="pubdate";
$z[7][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[8]=Array("adminname","",1475,1492);
$z[9]=Array("field","",1544,1571);
$z[9][4]['name']="phpurl";
$z[10]=Array("field","",1595,1618);
$z[10][4]['name']="id";
$z[11]=Array("field","",1623,1647);
$z[11][4]['name']="mid";
$z[12]=Array("field","",1813,1831);
$z[12][4]['name']="body";
$z[13]=Array("type","<a class=\"\" href=\"[field:typeurl/]\">返回上级</a>",1893,1979);
$z[13][4]['typeid']="5";
$z[14]=Array("include","",2010,2047);
$z[14][4]['filename']="footer.htm";

?>