<?php
$z[0]=Array("field","",201,223);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",263,315);
$z[1][4]['name']="description";
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("field","",740,759);
$z[2][4]['name']="title";
$z[3]=Array("global","",760,786);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",892,927);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",940,976);
$z[5][4]['filename']="head2.htm";
$z[6]=Array("field","",1086,1108);
$z[6][4]['name']="typename";
$z[7]=Array("type","[field:enwords /]",1133,1184);
$z[7][4]['typeid']="6";
$z[8]=Array("field","",1261,1280);
$z[8][4]['name']="title";
$z[9]=Array("field","",1320,1376);
$z[9][4]['name']="pubdate";
$z[9][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[10]=Array("field","",1392,1410);
$z[10][4]['name']="body";
$z[11]=Array("type","<a class=\"\" href=\"[field:typeurl/]\">返回上级</a>",1468,1554);
$z[11][4]['typeid']="6";
$z[12]=Array("include","",1576,1613);
$z[12][4]['filename']="footer.htm";

?>