<?php
$z[0]=Array("field","",201,223);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",263,315);
$z[1][4]['name']="description";
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("field","",740,759);
$z[2][4]['name']="title";
$z[3]=Array("global","",760,786);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",890,925);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",939,975);
$z[5][4]['filename']="head2.htm";
$z[6]=Array("field","",1166,1185);
$z[6][4]['name']="title";
$z[7]=Array("field","",1223,1279);
$z[7][4]['name']="pubdate";
$z[7][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[8]=Array("field","",1331,1358);
$z[8][4]['name']="phpurl";
$z[9]=Array("field","",1382,1405);
$z[9][4]['name']="id";
$z[10]=Array("field","",1410,1434);
$z[10][4]['name']="mid";
$z[11]=Array("field","",1612,1630);
$z[11][4]['name']="body";
$z[12]=Array("type","<a class=\"\" href=\"[field:typeurl/]\">返回上级</a>",1699,1785);
$z[12][4]['typeid']="4";
$z[13]=Array("include","",1816,1853);
$z[13][4]['filename']="footer.htm";

?>