<li>
					<a class="clearfix pop_box" href="[field:arcurl/]"> <!-- [field:arcurl/] -->
						<img class="fl" src="[field:picname/]" alt="[field:title/]" />
						<div class="fr cont">
							 <h5 class="clearfix">[field:title/]<span class="fr"> [field:pubdate function=strftime('%Y-%m-%d',@me)/]</span></h5>
							 <div class="deta">[field:infos/]
							 </div>
							 <div class="more clearfix"><span class="fr">more<i></i></span></div>
						</div>
					</a>
				</li>