<?php
$z[0]=Array("field","",242,271);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",311,370);
$z[1][4]['name']="description";
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("field","",795,814);
$z[2][4]['name']="title";
$z[3]=Array("global","",815,841);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",945,980);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",992,1028);
$z[5][4]['filename']="head2.htm";
$z[6]=Array("field","",1138,1160);
$z[6][4]['name']="typename";
$z[7]=Array("field","",1185,1206);
$z[7][4]['name']="enwords";
$z[8]=Array("list","  \r\n                                    		<li  class=\"third\" >\r\n					<a href=\"[field:arcurl/]\">\r\n						<img src=\"[field:picname/]\" alt=\"[field:title/]\" />\r\n						<span class=\"dept\"></span>\r\n						<span class=\"ars clearfix\">\r\n							<span class=\"fl\" title=\"[field:title/]\">[field:title/]</span>\r\n							<span class=\"fr\">more<i></i></span>\r\n						</span>\r\n					</a>\r\n				</li>\r\n			  				\r\n                 ",1466,1907);
$z[8][4]['pagesize']="6";
$z[9]=Array("pagelist","",1976,2042);
$z[9][4]['listitem']="index,end,pre,next,pageno";
$z[9][4]['listsize']="3";
$z[10]=Array("include","",2091,2128);
$z[10][4]['filename']="footer.htm";

?>