<?php
$z[0]=Array("global","",109,134);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("channelartlist","<ul id=\"dropmenu{dede:field.typeid/}\" class=\"dropMenu\">\r\n\r\n  {dede:channel type='son' noself='yes'}  <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n\r\n  {/dede:channel}\r\n\r\n</ul>\r\n\r\n",177,451);
$z[1][4]['typeid']="top";
$z[1][4]['cacheid']="channelsonlist";
$z[2]=Array("channel","\r\n<li><a href='[field:typelink/]'>[field:typename/]</a> </li>\r\n                ",1656,1784);
$z[2][4]['type']="top";
$z[2][4]['row']="8";
$z[3]=Array("global","",1887,1913);
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("flink","",1956,1977);
$z[4][4]['row']="4";

?>