<?php
$z[0]=Array("global","",856,881);
$z[0][4]['name']="cfg_weixin";
$z[1]=Array("global","",941,962);
$z[1][4]['name']="cfg_qq";
$z[2]=Array("global","",1008,1032);
$z[2][4]['name']="cfg_weibo";
$z[3]=Array("channel","\r\n<li><a href='[field:typelink/]'>[field:typename/]</a> </li>\r\n                ",1153,1281);
$z[3][4]['type']="top";
$z[3][4]['row']="5";
$z[4]=Array("global","",1393,1419);
$z[4][4]['name']="cfg_powerby";
$z[5]=Array("flink","",1601,1622);
$z[5][4]['row']="4";

?>