<?php
$z[0]=Array("global","",858,883);
$z[0][4]['name']="cfg_weixin";
$z[1]=Array("global","",943,964);
$z[1][4]['name']="cfg_qq";
$z[2]=Array("global","",1010,1034);
$z[2][4]['name']="cfg_weibo";
$z[3]=Array("channel","\r\n<li><a href='[field:typelink/]'>[field:typename/]</a> </li>\r\n                ",1155,1283);
$z[3][4]['type']="top";
$z[3][4]['row']="5";
$z[4]=Array("global","",1395,1421);
$z[4][4]['name']="cfg_powerby";
$z[5]=Array("flink","",1603,1624);
$z[5][4]['row']="4";

?>