<?php
$z[0]=Array("global","",91,118);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",217,244);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("channel","\r\n					<li><a href='[field:typelink/]' [field:rel/]>[field:typename/]</a>\r\n					</li>\r\n",263,481);
$z[2][4]['type']="top";
$z[2][4]['row']="6";
$z[2][4]['currentstyle']="<li class='current'><a href='~typelink~' ~rel~>~typename~</a> </li>";
$z[3]=Array("global","",571,596);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("channel","\r\n<li><a href='[field:typeurl/]' [field:rel/]><span class='bg_left'>[field:typename/]</span></a></li>\r\n",644,904);
$z[4][4]['type']="top";
$z[4][4]['row']="8";
$z[4][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span class='bg_left'>~typename~</span></a></li>";

?>