<?php
$z[0]=Array("global","",86,113);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",186,213);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("channel","\r\n                                                               <li><a href='[field:typelink/]'>[field:typename/]</a> </li>\r\n                ",248,515);
$z[2][4]['type']="top";
$z[2][4]['row']="6";
$z[2][4]['currentstyle']="<li class='current'><a href='~typelink~'>~typename~</a> </li>";

?>