<?php
$z[0]=Array("field","",201,230);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",270,329);
$z[1][4]['name']="description";
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("field","",754,773);
$z[2][4]['name']="title";
$z[3]=Array("global","",774,800);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",904,939);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",951,987);
$z[5][4]['filename']="head2.htm";
$z[6]=Array("type","[field:typename /]",1097,1149);
$z[6][4]['typeid']="5";
$z[7]=Array("type","[field:enwords /]",1174,1225);
$z[7][4]['typeid']="5";
$z[8]=Array("channel","\r\n<li><a href='[field:typelink/]'>[field:typename/]</a> </li>",1340,1526);
$z[8][4]['typeid']="5";
$z[8][4]['row']="2";
$z[8][4]['currentstyle']="<li class='hover'><a href='~typelink~' >~typename~</a> </li>";
$z[9]=Array("list","  	\r\n                        		<li>\r\n					<a class=\"clearfix pop_box\" href=\"[field:arcurl/]\"> <!-- [field:arcurl/] -->\r\n						<img class=\"fl\" src=\"[field:picname/]\" alt=\"[field:title/]\" />\r\n						<div class=\"fr cont\">\r\n							 <h5 class=\"clearfix\">[field:title/]<span class=\"fr\"> [field:pubdate function=strftime('%Y-%m-%d',@me)/]</span></h5>\r\n							 <div class=\"deta\">[field:infos/]\r\n							 </div>\r\n							 <div class=\"more clearfix\"><span class=\"fr\">more<i></i></span></div>\r\n						</div>\r\n					</a>\r\n				</li>\r\n					",1664,2222);
$z[9][4]['pagesize']="5";
$z[10]=Array("pagelist","",2265,2331);
$z[10][4]['listitem']="index,end,pre,next,pageno";
$z[10][4]['listsize']="3";
$z[11]=Array("include","",2381,2418);
$z[11][4]['filename']="footer.htm";

?>