<?php
$z[0]=Array("field","",176,195);
$z[0][4]['name']="title";
$z[1]=Array("global","",196,222);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",264,293);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",333,392);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",904,939);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",952,988);
$z[5][4]['filename']="head2.htm";
$z[6]=Array("channel","\r\n<li><a href='[field:typelink/]'>[field:typename/]</a> </li>\r\n",1267,1455);
$z[6][4]['typeid']="2";
$z[6][4]['row']="8";
$z[6][4]['currentstyle']="<li class='hover'><a href='~typelink~' >~typename~</a> </li>";
$z[7]=Array("list","\r\n                        \r\n           				<li  class=\"fourth\"><a  class=\"mian\"  href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" alt=\"[field:title/]\" /></a>\r\n					<div class=\"despt\">\r\n						<span class=\"fl\">[field:title/]</span>\r\n						<a class=\"fr\" href=\"[field:arcurl/]\">详情<i></i></a>\r\n					</div> \r\n				</li>\r\n		   				",1815,2181);
$z[7][4]['pagesize']="8";
$z[8]=Array("pagelist","",2249,2315);
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[8][4]['listsize']="3";
$z[9]=Array("include","",2362,2399);
$z[9][4]['filename']="footer.htm";

?>