<?php
$z[0]=Array("field","",174,193);
$z[0][4]['name']="title";
$z[1]=Array("global","",194,220);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",262,291);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",331,390);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",902,937);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",950,986);
$z[5][4]['filename']="head2.htm";
$z[6]=Array("channel","\r\n<li><a href='[field:typelink/]'>[field:typename/]</a> </li>\r\n",1265,1454);
$z[6][4]['typeid']="35";
$z[6][4]['row']="8";
$z[6][4]['currentstyle']="<li class='hover'><a href='~typelink~' >~typename~</a> </li>";
$z[7]=Array("list","\r\n                        \r\n           				<li  class=\"fourth\"><a  class=\"mian\"  href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" alt=\"[field:title/]\" /></a>\r\n					<div class=\"despt\">\r\n						<span class=\"fl\">[field:title/]</span>\r\n						<a class=\"fr\" href=\"[field:arcurl/]\">详情<i></i></a>\r\n					</div> \r\n				</li>\r\n		   				",1814,2180);
$z[7][4]['pagesize']="8";
$z[8]=Array("pagelist","",2248,2314);
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[8][4]['listsize']="3";
$z[9]=Array("include","",2361,2398);
$z[9][4]['filename']="footer.htm";

?>