<?php
$z[0]=Array("field","",201,230);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",270,329);
$z[1][4]['name']="description";
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("field","",754,773);
$z[2][4]['name']="title";
$z[3]=Array("global","",774,800);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",906,941);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",979,1015);
$z[5][4]['filename']="head2.htm";
$z[6]=Array("type","[field:typename /]",1134,1186);
$z[6][4]['typeid']="3";
$z[7]=Array("type","[field:enwords /]",1211,1262);
$z[7][4]['typeid']="3";
$z[8]=Array("channel","\r\n<li><a href='[field:typelink/]'>[field:typename/]</a> </li>\r\n",1401,1589);
$z[8][4]['typeid']="3";
$z[8][4]['row']="8";
$z[8][4]['currentstyle']="<li class='hover'><a href='~typelink~' >~typename~</a> </li>";
$z[9]=Array("field","",1828,1850);
$z[9][4]['name']="typename";
$z[10]=Array("field","",1945,2004);
$z[10][4]['name']="description";
$z[10][4]['function']="html2text(@me)";
$z[11]=Array("field","",2090,2111);
$z[11][4]['name']="content";
$z[12]=Array("arclist","\r\n                            <li>\r\n			<img src=\"[field:picname/]\" alt=\"\" />\r\n			<a class=\"hover\" href=\"[field:arcurl/]\"><span class=\"dest\"><span>[field:title/]</span><span class=\"more\">more<i></i></span></span></a>\r\n		</li>  \r\n        \r\n	    	  ",2247,2573);
$z[12][4]['typeid']="4";
$z[12][4]['row']="4";
$z[12][4]['titlelen']="16";
$z[12][4]['orderby']="rand";
$z[13]=Array("include","",2629,2666);
$z[13][4]['filename']="footer.htm";

?>