<?php
$z[0]=Array("field","",199,228);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",268,327);
$z[1][4]['name']="description";
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("field","",752,771);
$z[2][4]['name']="title";
$z[3]=Array("global","",772,798);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",904,939);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",977,1013);
$z[5][4]['filename']="head2.htm";
$z[6]=Array("type","[field:typename /]",1132,1185);
$z[6][4]['typeid']="30";
$z[7]=Array("type","[field:enwords /]",1210,1262);
$z[7][4]['typeid']="30";
$z[8]=Array("channel","\r\n<li><a href='[field:typelink/]'>[field:typename/]</a> </li>\r\n",1401,1590);
$z[8][4]['typeid']="30";
$z[8][4]['row']="8";
$z[8][4]['currentstyle']="<li class='hover'><a href='~typelink~' >~typename~</a> </li>";
$z[9]=Array("field","",1829,1851);
$z[9][4]['name']="typename";
$z[10]=Array("field","",1946,2005);
$z[10][4]['name']="description";
$z[10][4]['function']="html2text(@me)";
$z[11]=Array("field","",2091,2112);
$z[11][4]['name']="content";
$z[12]=Array("arclist","\r\n                            <li>\r\n			<img src=\"[field:picname/]\" alt=\"\" />\r\n			<a class=\"hover\" href=\"[field:arcurl/]\"><span class=\"dest\"><span>[field:title/]</span><span class=\"more\">more<i></i></span></span></a>\r\n		</li>  \r\n        \r\n	    	  ",2248,2575);
$z[12][4]['typeid']="34";
$z[12][4]['row']="4";
$z[12][4]['titlelen']="16";
$z[12][4]['orderby']="rand";
$z[13]=Array("include","",2631,2668);
$z[13][4]['filename']="footer.htm";

?>