<?php
$z[0]=Array("field","",201,230);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",270,329);
$z[1][4]['name']="description";
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("field","",754,773);
$z[2][4]['name']="title";
$z[3]=Array("global","",774,800);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",905,940);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",952,988);
$z[5][4]['filename']="head2.htm";
$z[6]=Array("field","",1098,1120);
$z[6][4]['name']="typename";
$z[7]=Array("field","",1145,1166);
$z[7][4]['name']="enwords";
$z[8]=Array("field","",1229,1250);
$z[8][4]['name']="content";
$z[9]=Array("list","  \r\n   	<li class=\"\"> \r\n		<span><a href=\"[field:arcurl/]\">[field:title/]</a></span>\r\n        <span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span><span><a href=\"[field:arcurl/]\">详请</a></span>\r\n	</li>\r\n     ",1453,1709);
$z[9][4]['pagesize']="118";
$z[10]=Array("include","",1766,1803);
$z[10][4]['filename']="footer.htm";

?>