<?php
$z[0]=Array("field","",199,228);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",268,327);
$z[1][4]['name']="description";
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("field","",752,771);
$z[2][4]['name']="title";
$z[3]=Array("global","",772,798);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",903,938);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",950,986);
$z[5][4]['filename']="head2.htm";
$z[6]=Array("field","",1096,1118);
$z[6][4]['name']="typename";
$z[7]=Array("field","",1143,1164);
$z[7][4]['name']="enwords";
$z[8]=Array("field","",1227,1248);
$z[8][4]['name']="content";
$z[9]=Array("list","  \r\n   	<li class=\"\"> \r\n		<span><a href=\"[field:arcurl/]\">[field:title/]</a></span>\r\n        <span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span><span><a href=\"[field:arcurl/]\">详请</a></span>\r\n	</li>\r\n     ",1451,1707);
$z[9][4]['pagesize']="118";
$z[10]=Array("include","",1764,1801);
$z[10][4]['filename']="footer.htm";

?>